packages:
  arch:
    paru:
      - fnm
      - vscode-langservers-extracted
      - brave-bin
      - mvppaper
    pacman:
      - exa
      - bat
      - zoxide
      - fzf
      - unzip
      - code
      - file-roller
      - gnome-clocks 
      - gnome-disk-utility
      - gnome-font-viewer
      - gnome-keyring
      - gnome-text-editor 
      - nautilus
      - seahorse
      - btop
      - smbclient
      - gvfs-smb
      - tailscale
      - tmux
      - fd
      - ttf-dejavu
      - ttf-liberation
      - ttf-droid
      - ttf-ubuntu-font-family
      - noto-fonts
      - docker
      - docker-compose
      - jq
      - fastfetch
      - wl-clipboard
      - xdg-desktop-portal-gtk
      - darkman
      - pavucontrol
      - less
      - nvtop
      - gvfs
      - swaync
      - tldr
      - neovim
      - git
      - zsh
      - nwg-displays
      - nwg-look
      - firefox
      - waybar
      - gnome-keyring
      - ttf-firacode-nerd
      - ttf-droid
